clc;
clear all;
close all;
real_array = [1, 2, 3, 4, 5];
complex_array = [1+1i, 2+2i, 3+3i, 4+4i, 5+5i];
figure;
subplot(2,2,1);
plot(real_array);
title('Continuous Plot Real Array');
xlabel('Index');
ylabel('Value');
subplot(2,2,2);
stem(real_array);
title('Stem Plot Real Array');
xlabel('Index');
ylabel('Value');
subplot(2,2,3);
plot(real_array, 'o');
hold on;
plot(imag(complex_array), '-x');
title('Continuous Plot Complex Array)');
xlabel('Index');
ylabel('Value');
legend('Real Part', 'Imaginary Part');
subplot(2,2,4);
stem(real(complex_array), 'filled');
hold on;
stem(imag(complex_array));
title('Stem Plot Complex Array');
xlabel('Index');
ylabel('Value');
legend('Real Part', 'Imaginary Part');