clc;
clear all;
close all;
t = 0:0.1:10;
a = sin(t);
b = cos(t);
c = sinh(t);
d = cosh(t);
subplot(4,1,1);
plot(t, a);
xlabel('time');
ylabel('sin(t)');
subplot(4,1,2);
plot(t, b);
xlabel('time');
ylabel('cos(t)');
subplot(4,1,3);
plot(t, c);
xlabel('time');
ylabel('sinh(t)');
subplot(4,1,4);
plot(t, d);
xlabel('time');
ylabel('cosh(t)');
