
clc;
clear all;
close all;
syms f1 f2 f3 f4 x
f1=sin(x);
f2=cos(x);
f3=sinh(x);
f4=cosh(x);
diff1 = diff(f1,x);
diff2 = diff(f2,x);
diff3 = diff(f3,x);
diff4 = diff(f4,x);
t = -10:0.01:10;
diffval1 = vpa(subs(diff1,x,t));
diffval2 = vpa(subs(diff2,x,t));
diffval3 = vpa(subs(diff3,x,t));
diffval4 = vpa(subs(diff4,x,t));
diff11 = diff(diff1,x);
diff21 = diff(diff2,x);
diff31 = diff(diff3,x);
diff41 = diff(diff4,x);
diffval11 = vpa(subs(diff11,x,t));
diffval21 = vpa(subs(diff21,x,t));
diffval31 = vpa(subs(diff31,x,t));
diffval41 = vpa(subs(diff41,x,t));
subplot(2,2,1);
plot(t,diffval11);
xlabel("Time");
ylabel("f''(sine(t))");
subplot(2,2,2);
plot(t,diffval21);
xlabel("Time");
ylabel("f''(cos(t))");
subplot(2,2,3);
plot(t,diffval31);
xlabel("Time");
ylabel("f''(sinh(t))");
subplot(2,2,4);
plot(t,diffval41);
xlabel("Time");
ylabel("f''(cosh(t))");